name: Android Emulator CI on Ubuntu

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Docker Android Action
      uses: faberNovel/docker-android@v1.1.1
      with:
        docker-android-tag: api-29-ndk-v1.1.0
        exec: |
          ./emu_docker.sh
          cd ui/espresso/BasicSample
          ./gradlew app:connectedDebugAndroidTes
